### ISSUE TITLE
TO DO - 11/27

### ISSUE THREAD

**Issue by kimyouilm** [kimyouilm/achievement-store#7]
- [ ] 프론트 전부 바꾸기
- [ ] 유저 - 사진등록
- [ ] 유저 - 계좌 이력등록
- [ ] 게시글 - 댓글 페이징 ajax 처리
- [ ] 댓글 - 삭제 기능
- [ ] 게시글 - 완료시, 실패시 필터 처리로 리스트에 보여주기
- [ ] 게시글 - 완료시, 실패시 리스트에 완료, 실패 라고 표시
- [ ] 스토어 - (관리자) 물건 등록
- [ ] 스토어 - 장바구니
- [ ] 스토어 - 물건 게시글 수정 & 삭제
- [ ] 스토어 - 결제

가능하다면

- [ ] 검색기능 넣어보기  
- [ ] 댓글 수정, 삭제 기능

**Comment by Soo77** [comment]
퍼가요~❤

**Comment by kimyouilm** [comment]
대부분 진행중이며 TODO 로 전환
